export let fileTypes = {
  'name':{
    label:'客户姓名',
    iconClass:'pre-icon-name'
  },
  'phone':{
    label:'手机号',
    iconClass:'pre-icon-phone'
  },
  'gender':{
    label:'客户性别',
    iconClass:'pre-icon-gender'
  },
  'id':{
    label:'身份证号',
    iconClass:'pre-icon-id'
  },
  'srxx':{
    label:'生日信息',
    iconClass:'pre-icon-srxx'
  },
  'wechat':{
    label:'微信号',
    iconClass:'pre-icon-wechat'
  },
  'khzt':{
    label:'客户状态',
    iconClass:'pre-icon-khzt'
  },
  'khly':{
    label:'客户来源',
    iconClass:'pre-icon-khly'
  },
  'hylx':{
    label:'会员类型',
    iconClass:'pre-icon-hylx'
  },
  'district':{
    label:'所在地区',
    iconClass:'pre-icon-district'
  },
  'bz':{
    label:'备注',
    iconClass:'pre-icon-bz'
  },
  'moreinfo':{
    label:'添加更多联系方式',
    iconClass:'pre-icon-moreinfo'
  },
  'email':{
    label:'邮箱',
    iconClass:'pre-icon-email'
  },
  'address':{
    label:'地址',
    iconClass:'pre-icon-address'
  },

  'sjname':{
    label:'商机名称',
    iconClass:'pre-icon-sjname'
  },
  'sjjb':{
    label:'商机级别',
    iconClass:'pre-icon-sjjb'
  },
  'date-deal':{
    label:'预计成交',
    iconClass:'pre-icon-date-deal'
  },
  'date-get':{
    label:'获取时间',
    iconClass:'pre-icon-date-get'
  },
  'price':{
    label:'商机金额',
    iconClass:'pre-icon-price'
  },
  'bussiorigin':{
    label:'商机来源',
    iconClass:'pre-icon-bussiorigin'
  },
  'status':{
    label:'商机名称',
    iconClass:'pre-icon-status'
  },
  'clerk':{
    label:'业务员',
    iconClass:'pre-icon-price'
  },

}